%\VignetteIndexEntry{Visualize and RNA-seq data normalization with the "NVT" package}
%\VignettePackage{NVT}
%\VignetteEngine{knitr::knitr}

% To compile this document
% library('knitr'); rm(list=ls()); knit('NVT.Rnw')

\documentclass[11pt]{article}

\newcommand{\nvt}{\textit{NVT}}
\newcommand{\lowtilde}{\raise.17ex\hbox{$\scriptstyle\mathtt{\sim}$}}

<<knitr, echo=FALSE, results="hide">>=
library("knitr")
opts_chunk$set(
  tidy=FALSE,
  dev="png",
  fig.show="hide",
  fig.width=4, fig.height=4.5,
  cache=TRUE,
  message=FALSE)
@

<<style-knitr, eval=TRUE, echo=FALSE, results="asis">>=
BiocStyle::latex()
@

\author{Thomas Eder$^{1,2}$, Thomas Rattei$^{1}$\\[1em]
  \small{$^{1}$ CUBE Division of Computational Systems Biology,} \\
  \small{Department of Microbiology and Ecosystem Science,} \\
  \small{University of Vienna, Althanstrasse 14, 1090 Vienna, Austria. } \\
  \small{$^{2}$ Ludwig Boltzmann Institute for Cancer Research,} \\
  \small{Waehringer Strasse 13A, 1090 Vienna, Austria.} }

\title{Visualization and evaluation of RNA-seq data normalization -- the Normalization Visualization Tool}

\begin{document}

\maketitle

\begin{abstract}

Differential expression analysis, between two samples, is a common task in the analysis of RNA-Seq data. In order to identify differential expressed genes it is crucial that the two compared data sets are normalized. For the task of normalizing gene expression data there are multiple methods available. But all of them are based on certain assumptions that can or can not be meet by the data which should be normalized. An important question is, how the normalization affects the data and which normalization method and its assumptions blend well with the expression data. The \nvt{} package provides a fast and simple way to analyze multiple normalization methods via visualization and correlation values. This vignette explains the use of the package and demonstrates a typical work flow.

  \vspace{1em}

  \textbf{NVT version:} \Sexpr{packageVersion("NVT")}

  \vspace{1em}

  \begin{center}
    \begin{tabular}{ | l | }
      \hline
      If you use \nvt{} in published research, please cite:  \\
      \\
      T. Eder, T.Rattei: \textbf{NVT: a fast and simple test for} \\
      \textbf{the evaluation of RNA-Seq normalization strategies}. \\
      \emph{Bioinformatics} 2016, \textbf{15}:550. \\
      \url{http://dx.doi.org/10.1186/s13059-014-0550-8}  \\
      \hline
    \end{tabular}
  \end{center}

\end{abstract}


\newpage

\tableofcontents

\newpage

\section{Installation}

Download the latest NVT package from: \url{https://github.com/NexusX/NVT/releases} and install it with the following command.

<<installNVT,  eval=FALSE>>=
install.packages(file.path("/home/user/Downloads/","NVT_1.0.tar.gz"),
repos=NULL, type="source")

@

\section{Standard work flow}

\subsection{Load data}

We need some gene expression data, load the example data provided with the package

<<loadNVT>>=
library("NVT")
@

\subsubsection{Load expression data}

load example data

<<loadExData>>=
data(mylen)
data(myexp1)
data(myexp2)
mylist1=c('CT462','CT115','CT045','CT678')
@

\subsubsection{Load gene length data}

Instead of using a simple flat file, it is also possible to load the gene or exon length data directly from an annotation file in gtf or gff format.

<<loadLengthData>>=
mygffpath<-system.file("extdata", "Ctr-D-UW3CX.gff", package = "NVT")
mylen <- NVTloadgff(mygffpath,"gff3","gene","locus_tag")
head(mylen)
@


\subsection{Generate NVTdata objects}

<<generateNVTobj>>=
mynvt <- NVTinit(mylist1,myexp1,myexp2,"RPKM",mylen)
@

\subsubsection{Normalize the NVTdata }

<<normlaizeNVTobj>>=
mynorm <- NVTnormalize(mynvt)
@

\subsection{Visualize expression data}

\subsubsection{Simple plot}

<<simpleplot>>=
png(filename = "figure/simpleplot.png", width = 580, height = 580, units = "px", pointsize = 12)
NVTplot(mynorm,1)
dev.off()
@

\begin{figure}
\centering
\includegraphics[width=.8\textwidth]{figure/simpleplot}
\caption{
  \textbf{Simple XY-Scatter-Plot.}
  This plot shows the simple NVT plot function result}
\label{fig:MA}
\end{figure}

\subsubsection{Advanced plot}

<<advancedplot>>=
png(filename = "figure/advancedplot.png", width = 580, height = 580, units = "px", pointsize = 12)
NVTadvancedplot(mynorm,2,2,4)
dev.off()
@

\begin{figure}
\centering
\includegraphics[width=.8\textwidth]{figure/advancedplot}
\caption{
  \textbf{Advanced XY-Scatter-Plot.}
  This plot shows the advanced NVT plot function result}
\label{fig:MA}
\end{figure}

\subsection{Correlation values}

\subsubsection{Pearson correlation}

\subsubsection{RMSD and MEA correlation}

\subsection{Test all methods}


\section{Acknowledgments}

We have benefited in the development of \nvt{} from the help and
feedback of many individuals,
\section{Session Info}

\bibliography{library}

\end{document}
